# Site settings
title: Wind's zone
email: wind@wind.com
description: >
  Like code.
baseurl: "jekyll_blog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: wind-twitter
github_username:  wind

# Build settings
markdown: kramdown

excerpt_separator: "\n\n\n"
safe: false
pygments: true
paginate: 5
